josh = User.create(username: "Josh", password: "Josh")
rachel = User.create(username: "Rachel", password: "Rachel")
avery = User.create(username: "Avery", password: "Mydoggy")
spencer = User.create(username: "Spencer", password: "Herdoggy")
woody = User.create(username: "Woody", password: "Woody")

golden_hour = Vinyl.create(title: "Golden Hour", artist: "Kacey Musgrave", genre: "Country", release_year: "2018", user: rachel)
malibu = Vinyl.create(title: "Malibu", artist: "Anderson Paak", genre: "Hip-Hop", release_year: "2016", user: josh)
golden_hour = Vinyl.create(title: "Golden Hour", artist: "Kacey Musgrave", genre: "Country", release_year: "2018", user: rachel)
golden_hour = Vinyl.create(title: "Golden Hour", artist: "Kacey Musgrave", genre: "Country", release_year: "2018", user: rachel)
golden_hour = Vinyl.create(title: "Golden Hour", artist: "Kacey Musgrave", genre: "Country", release_year: "2018", user: rachel)
golden_hour = Vinyl.create(title: "Golden Hour", artist: "Kacey Musgrave", genre: "Country", release_year: "2018", user: rachel)
golden_hour = Vinyl.create(title: "Golden Hour", artist: "Kacey Musgrave", genre: "Country", release_year: "2018", user: rachel)
golden_hour = Vinyl.create(title: "Golden Hour", artist: "Kacey Musgrave", genre: "Country", release_year: "2018", user: rachel)
golden_hour = Vinyl.create(title: "Golden Hour", artist: "Kacey Musgrave", genre: "Country", release_year: "2018", user: rachel)

