josh = User.create(username: "Josh", password: "Josh")
rachel = User.create(username: "Rachel", password: "Rachel")
avery = User.create(username: "Avery", password: "Mydoggy")
spencer = User.create(username: "Spencer", password: "Herdoggy")
woody = User.create(username: "Woody", password: "Woody")

golden_hour = Vinyl.create(title: "Golden Hour", artist: "Kacey Musgrave", genre: "Country", release_year: "2018", user: rachel)
malibu = Vinyl.create(title: "Malibu", artist: "Anderson Paak", genre: "Hip-Hop", release_year: "2016", user: josh)
led_zeppelin = Vinyl.create(title: "Led Zeppelin", artist: "Led Zeppelin", genre: "Classic Rock", release_year: "1969", user: josh)
led_zeppelin_4 = Vinyl.create(title: "Led Zeppelin IV", artist: "Led Zeppelin", genre: "Classic Rock", release_year: "2071", user: josh)
doggystyle = Vinyl.create(title: "Doggy Style", artist: "Snoop Dogg", genre: "Hip-Hop", release_year: "1993", user: spencer)
who_let_the_dogs_out = Vinyl.create(title: "Who Let the Dogs Out", artist: "Baha Men", genre: "Hip-Hop", release_year: "2000", user: avery)
rumours = Vinyl.create(title: "Rumours", artist: "Fleetwood Mac", genre: "Classic Rock", release_year: "1977", user: woody)
the_mouse_and_the_mask = Vinyl.create(title: "The Mouse and the Mask", artist: "Danger Doom", genre: "Hip-Hop", release_year: "2005", user: woody)
watermark = Vinyl.create(title: "Watermark", artist: "Enya", genre: "Pop", release_year: "1988", user: rachel)

